#!/usr/bin/env python3
"""Convert Playwright storage_state JSON to Netscape cookies.txt for yt-dlp.

Usage:
    python cookie_convert.py .instagram_session instagram_cookies.txt

Notes:
- Playwright saves cookies in proprietary JSON under .instagram_session.
- yt-dlp expects Netscape cookies.txt format (--cookies path).
- This script maps domain, path, secure, expires, name, value.
- Session cookies (expires=-1) are mapped to max epoch (2147483647) so
  yt-dlp treats them as valid rather than discarding them.
"""
import json
import sys
from pathlib import Path

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by cookie_convert.py — do not edit manually.\n"
    "# Format: domain [TAB] include_subdomains [TAB] path [TAB] secure [TAB] expiry [TAB] name [TAB] value\n"
)


def convert(storage_path: Path, output_path: Path) -> int:
    data = json.loads(storage_path.read_text(encoding="utf-8"))
    cookies = data.get("cookies", [])
    if not cookies:
        raise ValueError(f"No cookies found in {storage_path}")

    lines = [NETSCAPE_HEADER]
    for c in cookies:
        domain = c.get("domain", "")
        # Netscape expects leading dot for domain-wide cookies.
        if domain and not domain.startswith(".") and c.get("hostOnly") is False:
            domain = "." + domain.lstrip(".")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires_raw = c.get("expires", -1)
        expires = 2147483647 if (expires_raw is None or expires_raw < 0) else int(expires_raw)
        name = c.get("name", "")
        value = c.get("value", "")
        if not domain or not name:
            continue
        lines.append(
            "\t".join([domain, include_subdomains, path, secure, str(expires), name, value])
        )
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(cookies)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python cookie_convert.py <storage_state.json> <output_cookies.txt>")
        sys.exit(1)
    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    if not src.exists():
        print(f"[FAIL] Input file not found: {src}")
        sys.exit(1)
    try:
        count = convert(src, dst)
        print(f"[OK] Converted {count} cookies -> {dst.resolve()}")
    except (ValueError, KeyError, json.JSONDecodeError) as e:
        print(f"[FAIL] {e}")
        sys.exit(1)
